export const CREATE_STOCK = {
  REQ_CREATE_STOCK: "REQ_CREATE_STOCK",
  SUCCESS_CREATE_STOCK: "SUCCESS_CREATE_STOCK",
  FAILURE_CREATE_STOCK: "FAILURE_CREATE_STOCK",
};

export const GET_STOCK = {
  REQ_GET_STOCK: "REQ_GET_STOCK",
  SUCCESS_GET_STOCK: "SUCCESS_GET_STOCK",
  CREATE_STOCK:"CREATE_STOCK",
  FAILURE_GET_STOCK: "FAILURE_GET_STOCK",
};

export const CREATE_ORDER = {
  REQ_CREATE_ORDER: "REQ_CREATE_ORDER",
  SUCCESS_CREATE_ORDER: "SUCCESS_CREATE_ORDER",
  FAILURE_CREATE_ORDER: "FAILURE_CREATE_ORDER",
};

export const GET_ORDER = {
  REQ_GET_ORDER: "REQ_GET_ORDER",
  SUCCESS_GET_ORDER: "SUCCESS_GET_ORDER",
  FAILURE_GET_ORDER: "FAILURE_GET_ORDER",
};
